theme: jekyll-theme-cayman
title: "Ꭵᑎ丅ᗴᖇᐯᎥᗴᗯᑭᖇᗴᑭ"
description: "A community driven platform for interview preparation"
include:
  - backend
  - devops
  - dsa
  - google
  - php
  - javascript
  - next
  - react

exclude:
  - /node_modules/
  - Gemfile.*
  - package.json
  - yarn.lock
plugins:
  - jekyll-feed
collections: {}
permalink: "/:path"
timezone: "Asia/Kolkata"
multilingual: false
language: en
languages:
  en: English
